import { useEffect, useState, type ReactNode } from 'react';
import { SignIn, UserButton, useAuth } from '@clerk/react';
import { useConvexAuth, useMutation, usePaginatedQuery, useQuery } from 'convex/react';
import { api } from '../convex/_generated/api';
import type { Doc, Id } from '../convex/_generated/dataModel';
import { EMPTY_ANSWERS, QUESTIONS, STATE_LABELS, isFinal, isFlagged, mean, type Profile, type ReviewState } from './domain';
import { AnswerSummary, ApplicationForm, Hero, Notice, ProfileFields, ReviewPanel, Status, errorMessage } from './ui';

export function Shell({ children, user, account }: { children: ReactNode; user?: Doc<'users'> | null; account?: ReactNode }) {
  const [theme, setTheme] = useState(() => localStorage.getItem('malaysianai-theme') === 'dark' || (localStorage.getItem('malaysianai-theme') !== 'light' && matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light');
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('malaysianai-theme', theme); }, [theme]);
  const path = window.location.pathname;
  return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><a className="brand" href="/" aria-label="Malaysian AI Residency home"><img src="/malaysian-ai-batik-logo-bw.svg" alt="" width="42" height="42" /><span>Malaysian AI<small>The Residency</small></span></a><nav aria-label="Main navigation">{user && <><a href="/profile" aria-current={path === '/profile' ? 'page' : undefined}>Profile</a><a href="/application" aria-current={['/apply', '/application'].includes(path) ? 'page' : undefined}>Application</a>{(user.resident || user.admin) && <a href="/admin" aria-current={path.startsWith('/admin') ? 'page' : undefined}>Resident room</a>}</>}<button className="theme-button" aria-label={theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'} onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? '☼' : '◐'}</button>{account}</nav></header><main id="main" className="site-main">{children}</main><footer className="site-footer"><div><img src="/malaysian-ai-batik-logo-bw.svg" width="32" height="32" alt="" /><span>Build in Malaysia.<br /><em>Ship for the world.</em></span></div><p>Kuala Lumpur, Malaysia<br /><a href="https://www.malaysian.ai">Back to Malaysian AI ↗</a></p><nav aria-label="Legal"><a href="https://www.malaysian.ai/privacy">Privacy</a><a href="https://www.malaysian.ai/terms">Terms</a></nav></footer></>;
}
export function SetupMissing() { return <Shell><Hero eyebrow="Malaysian AI / The Residency" title={<>A home for<br /><em>your next chapter.</em></>} description="The application platform is being connected. Please return shortly." /><Notice>Sign-in is not configured yet. No application data has been collected.</Notice></Shell>; }
export default function App() {
  const { isLoaded, isSignedIn } = useAuth();
  if (!isLoaded) return <Shell><Loading /></Shell>;
  if (!isSignedIn) return <Shell><div className="welcome"><div className="welcome-copy"><p className="eyebrow">The Malaysian AI Residency</p><h1>Find your people.<br /><em>Build your thing.</em></h1><p className="lede">A working home for curious, committed people building what comes next.</p><div className="welcome-caption"><span className="section-number">↗</span><p>Start with your story.<br />A few questions. An honest conversation.</p></div><div className="welcome-photo"><img src="/residency.jpg" alt="Builders of different ages learning together at Malaysian AI" /><span>Kuala Lumpur, Malaysia</span></div></div><div className="auth-panel"><p className="eyebrow">Your next chapter starts here</p><SignIn routing="hash" fallbackRedirectUrl="/profile" /><p className="hint">Your profile and application are private to you and our resident community.</p></div></div></Shell>;
  return <MemberApp />;
}
function Loading() { return <div className="loading" role="status"><span className="loading-mark">✳</span><p>Getting your space ready…</p></div>; }
function MemberApp() {
  const auth = useConvexAuth();
  const user = useQuery(api.users.me, auth.isAuthenticated ? {} : 'skip');
  const ensure = useMutation(api.users.ensure);
  const [error, setError] = useState(''); const [attempt, setAttempt] = useState(0);
  useEffect(() => { if (auth.isAuthenticated) ensure({}).catch(err => setError(errorMessage(err))); }, [auth.isAuthenticated, ensure, attempt]);
  return <Shell user={user} account={<UserButton />}>{error ? <><Notice error>{error}</Notice><button className="button secondary" onClick={() => { setError(''); setAttempt(value => value + 1); }}>Try again</button></> : !auth.isLoading && !auth.isAuthenticated ? <Notice error>Sign-in succeeded, but the application server could not verify your session. Please reload this page. If this continues, contact the residency team.</Notice> : !user ? <Loading /> : <Routes user={user} />}</Shell>;
}
function Routes({ user }: { user: Doc<'users'> }) {
  const path = window.location.pathname.replace(/\/$/, '') || '/';
  if (path.startsWith('/admin') && !user.resident && !user.admin) return <><Hero eyebrow="Private resident room" title="Resident access required." description="Your account has not been granted access to review applications." /><a className="button" href="/profile">Return to your profile</a></>;
  if (path === '/admin/residents' && user.admin) return <ResidentAccess />;
  if (path.startsWith('/admin/applications/')) return <ReviewPage id={path.split('/').pop() as Id<'applications'>} user={user} />;
  if (path === '/admin') return <Dashboard user={user} />;
  if (path === '/apply' || path === '/application') return <ApplicantPage user={user} />;
  if (path === '/' || path === '/profile') return <ProfilePage user={user} />;
  return <><Hero eyebrow="Page not found" title="A small detour." description="This page doesn’t exist. Your profile is a good place to start." /><a className="button" href="/profile">Your profile ↗</a></>;
}
function ProfilePage({ user }: { user: Doc<'users'> }) {
  const [profile, setProfile] = useState<Profile>(user.profile);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const save = useMutation(api.users.saveProfile); const app = useQuery(api.applications.mine);
  return <><Hero eyebrow="Your corner of Malaysian AI" title={<>Hello, <em>{user.profile.name.split(' ')[0] || 'builder'}.</em></>} description="A little context for the people you’ll build alongside. This profile is yours to keep up to date." /><div className="profile-layout"><form onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { await save({ profile }); setMessage('Your profile has been saved.'); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }}><div className="section-heading"><span className="section-number">01</span><h2>Your details</h2></div><ProfileFields profile={profile} setProfile={setProfile} email={user.email} complete={false} /><div className="section-heading social-heading"><span className="section-number">02</span><h2>Find you elsewhere</h2></div><ProfileFields profile={profile} setProfile={setProfile} email={user.email} socials />{message && <Notice>{message}</Notice>}{error && <Notice error>{error}</Notice>}<button className="button" disabled={busy}>{busy ? 'Saving…' : 'Save profile'} <span>↗</span></button></form><aside className="profile-card"><p className="eyebrow">Your next chapter</p><span className="large-asterisk" aria-hidden="true">✳</span><h2>The Residency</h2><p>Bring the thing you can’t stop thinking about. Find a room that helps you take it further.</p>{app && <Status state={app.state} />}<a className="button full" href={app && app.state !== 'draft' ? '/application' : '/apply'}>{app ? app.state === 'draft' ? 'Continue application' : 'View application' : 'Begin application'} <span>↗</span></a><p className="hint">Your profile stays private. Submitted application details are saved as a separate, permanent snapshot.</p></aside></div></>;
}
function ApplicantPage({ user }: { user: Doc<'users'> }) {
  const app = useQuery(api.applications.mine);
  const save = useMutation(api.applications.saveDraft); const submit = useMutation(api.applications.submit);
  if (app === undefined) return <Loading />;
  if (app && app.state !== 'draft') return <><Hero eyebrow="Your residency application" title={app.state === 'accepted' ? <>Welcome to<br /><em>your next chapter.</em></> : app.state === 'rejected' ? <>Thank you for<br /><em>sharing your work.</em></> : <>Your story is<br /><em>with our residents.</em></>} description={app.state === 'accepted' ? 'Your application has been accepted. The team will be in touch about joining.' : app.state === 'rejected' ? 'We’re unable to offer you a place this time. We appreciate the time and thought you put into applying.' : 'You can follow the outcome here. We’ll also email you when a final decision is made.'}><Status state={app.state} /><p className="hint">Submitted {formatDate(app.submittedAt)} · Your submitted answers are locked.</p></Hero><div className="submitted-answers"><AnswerSummary profile={app.profile} answers={app.answers} email={app.email} /></div></>;
  return <ApplicationForm initialProfile={user.profile} initialAnswers={app?.answers ?? EMPTY_ANSWERS} email={user.email} onSave={(profile, answers) => save({ profile, answers })} onSubmit={(profile, answers) => submit({ profile, answers })} />;
}
function Dashboard({ user }: { user: Doc<'users'> }) {
  const [search, setSearch] = useState(''); const [state, setState] = useState<ReviewState | ''>(''); const [filter, setFilter] = useState('all');
  const { results, status, loadMore } = usePaginatedQuery(api.applications.list, { search, ...(state ? { state } : {}) }, { initialNumItems: 25 });
  const rows = results.filter(row => filter === 'flagged' ? row.application.flagged : filter === 'mine' ? !isFinal(row.application.state) && row.application.voters.includes(user._id) && !row.reviews.some(review => review.reviewer === user._id) : true);
  return <><Hero eyebrow="The resident room" title={<>Who builds<br /><em>alongside us?</em></>} description="Read the work. Bring your perspective. Make the decision together."><div className="actions"><span className="room-label"><span className="save-dot" /> Live review room</span>{user.admin && <a className="text-link" href="/admin/residents">Manage residents ↗</a>}</div></Hero><div className="dashboard-tools"><div className="search-field"><label htmlFor="search">Find an applicant</label><input type="search" id="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search by name…" /></div><div className="filter-field"><label htmlFor="state">Application status</label><select id="state" value={state} onChange={event => setState(event.target.value as ReviewState | '')}><option value="">All statuses</option>{Object.entries(STATE_LABELS).filter(([key]) => key !== 'draft').map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><div className="filter-field"><label htmlFor="filter">Review focus</label><select id="filter" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">Everyone</option><option value="mine">Awaiting my vote</option><option value="flagged">Flagged reviews</option></select></div></div><div className="queue-heading"><p className="eyebrow">Applications</p><span>{rows.length} shown{status !== 'Exhausted' ? ' · load more below' : ''}</span></div><div className="application-queue">{rows.map(({ application: app, reviews }) => {
    const scored = reviews.filter(review => review.scores !== null);
    return <a className="application-row" key={app._id} href={`/admin/applications/${app._id}`}><div className="applicant-monogram">{app.profile.name.slice(0, 1)}</div><div className="applicant-info"><h2>{app.profile.name}</h2><p>{app.profile.roles.slice(0, 2).join(' · ')}</p><small>Submitted {formatDate(app.submittedAt)}</small></div><div className="row-progress"><strong>{reviews.length}<span> / {app.voters.length} responded</span></strong><progress value={reviews.length} max={Math.max(app.voters.length, 1)} aria-label="Resident responses" /><small>{reviews.filter(r => r.decision === 'yes').length} Yes · {reviews.filter(r => r.decision === 'no').length} No · {reviews.filter(r => r.decision === 'abstain').length} Abstain</small></div><div className="row-score"><strong>{scored.length ? (scored.reduce((sum, review) => sum + mean(review.scores!), 0) / scored.length).toFixed(1) : '—'}</strong><small>Average / 10</small></div><div className="row-status"><Status state={app.state} />{app.flagged && <span className="flag-label">⚑ High score, No vote</span>}</div><span className="row-arrow" aria-hidden="true">↗</span></a>;
  })}</div>{status === 'LoadingFirstPage' ? <Loading /> : !rows.length && <div className="empty-state"><span>✳</span><h2>{results.length ? 'No matches in this page.' : 'A little quiet, for now.'}</h2><p>{results.length ? 'Adjust your filters or load more applications.' : 'New applications will appear here when they’re submitted.'}</p></div>}{status !== 'Exhausted' && <button className="button secondary" disabled={status !== 'CanLoadMore'} onClick={() => loadMore(25)}>{status === 'CanLoadMore' ? 'Load more applications' : 'Loading…'}</button>}{user.admin && <EmailFailures />}</>;
}
function ReviewPage({ id, user }: { id: Id<'applications'>; user: Doc<'users'> }) {
  const data = useQuery(api.applications.detail, { id }); const save = useMutation(api.applications.saveReview);
  if (!data) return <Loading />;
  const app = data.application; const own = data.reviews.find(review => review.reviewer === user._id);
  const scored = data.reviews.filter(review => review.scores !== null);
  return <><a className="back-link" href="/admin">← All applications</a><Hero eyebrow="Application / Resident review" title={app.profile.name} description={app.profile.roles.join(' · ')}><Status state={app.state} /><p className="hint">Submitted {formatDate(app.submittedAt)} · {data.reviews.length} of {app.voters.length} residents have responded</p></Hero><div className="review-layout"><div><AnswerSummary profile={app.profile} answers={app.answers} email={app.email} /><section className="resident-votes"><p className="eyebrow">Every perspective counts</p><h2>The room’s read</h2>{scored.length > 0 && <div className="category-averages">{(['obsession', 'vibes', 'executionPace'] as const).map((key, index) => <div key={key}><small>{['Obsession', 'Vibes', 'Execution pace'][index]}</small><strong>{(scored.reduce((sum, review) => sum + review.scores![key], 0) / scored.length).toFixed(1)}<span> / 10</span></strong></div>)}</div>}{data.voters.map(person => {
    const review = data.reviews.find(item => item.reviewer === person.id);
    return <div className="resident-vote" key={person.id}><div className="vote-heading"><strong>{person.name}{!person.active ? ' · inactive' : ''}</strong><span className={`badge ${review?.decision ?? ''}`}>{review ? review.decision : 'Awaiting vote'}</span></div>{review?.scores && <p className="vote-scores">Obsession {review.scores.obsession} · Vibes {review.scores.vibes} · Pace {review.scores.executionPace}<strong>{mean(review.scores).toFixed(2)} average</strong></p>}{review && isFlagged(review) && <p className="flag-label">⚑ High score, No vote</p>}{review?.reason && <p className="preserve">{review.reason}</p>}</div>;
  })}{!app.voters.length && <Notice error>No residents are assigned. An admin must configure the panel before any decision.</Notice>}</section><details className="history"><summary>Review history <span>Most recent 50 events</span></summary>{data.history.map(event => <article key={event._id}><strong>{event.kind.replaceAll('_', ' ')}</strong><small>{formatDate(event._creationTime)} · {data.voters.find(person => person.id === event.actor)?.name ?? 'Applicant / admin'}</small><p className="preserve">{event.detail}</p></article>)}</details></div><aside>{app.voters.includes(user._id) && user.resident ? <ReviewPanel key={`${id}-${isFinal(app.state)}`} initial={own} locked={isFinal(app.state)} onSave={vote => save({ id, ...vote })} /> : <div className="review-panel"><h2>{isFinal(app.state) ? 'Decision recorded' : 'Following the review'}</h2><p>You are not an active voter on this application’s panel.</p></div>}{user.admin && !isFinal(app.state) && <AdminResolution app={app} />}{user.admin && !isFinal(app.state) && <RosterEditor app={app} voters={data.voters} reviews={data.reviews} />}{isFinal(app.state) && <Notice>Final decision recorded {formatDate(app.decidedAt)}. {app.decisionReason}</Notice>}</aside></div></>;
}
function AdminResolution({ app }: { app: Doc<'applications'> }) {
  const resolve = useMutation(api.applications.resolve); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const ready = app.state === 'admin_resolution' || app.state === 'discussion';
  if (!ready) return null;
  async function decide(decision: 'accepted' | 'rejected') { setBusy(true); setError(''); try { await resolve({ id: app._id, decision, reason }); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }
  return <div className="admin-resolution"><p className="eyebrow">Designated admin</p><h2>{app.state === 'discussion' ? 'A conversation first.' : 'Resolve the abstentions.'}</h2><p>{app.state === 'discussion' ? 'A No vote blocks acceptance. Discuss the concerns before finalizing rejection. Only the resident can revise their vote.' : 'Everyone has responded and nobody voted No. Record the outcome and why.'}</p><label htmlFor="resolution-reason">Internal decision reason</label><textarea id="resolution-reason" maxLength={4000} rows={4} value={reason} onChange={event => setReason(event.target.value)} />{error && <Notice error>{error}</Notice>}<div className="actions">{app.state === 'admin_resolution' && <button className="button" disabled={busy || !reason.trim()} onClick={() => decide('accepted')}>Accept</button>}<button className="button danger" disabled={busy || !reason.trim()} onClick={() => decide('rejected')}>Finalize rejection</button></div><p className="hint">This records a final decision and queues an applicant email.</p></div>;
}
function RosterEditor({ app, voters, reviews }: { app: Doc<'applications'>; voters: { id: Id<'users'>; name: string }[]; reviews: Doc<'reviews'>[] }) {
  const residents = useQuery(api.users.residents); const change = useMutation(api.applications.changeRoster); const [replace, setReplace] = useState(''); const [add, setAdd] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <details className="roster-editor"><summary>Manage this review panel</summary><p className="hint">Existing votes cannot be removed. Membership changes are recorded.</p><form onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { await change({ id: app._id, replace: replace ? replace as Id<'users'> : null, add: add as Id<'users'>, reason }); setAdd(''); setReplace(''); setReason(''); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }}><label htmlFor="replace">Replace an unvoted resident</label><select id="replace" value={replace} onChange={event => setReplace(event.target.value)}><option value="">Add without replacing</option>{voters.filter(person => !reviews.some(review => review.reviewer === person.id)).map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select><label htmlFor="add">Active resident</label><select id="add" required value={add} onChange={event => setAdd(event.target.value)}><option value="">Choose a resident</option>{residents?.filter(person => !app.voters.includes(person._id) && person._id !== app.owner).map(person => <option value={person._id} key={person._id}>{person.profile.name || person.email}</option>)}</select><label htmlFor="roster-reason">Reason</label><textarea id="roster-reason" required maxLength={2000} value={reason} onChange={event => setReason(event.target.value)} />{error && <Notice error>{error}</Notice>}<button className="button secondary" disabled={busy}>Update panel</button></form></details>;
}
function ResidentAccess() {
  const [search, setSearch] = useState(''); const [email, setEmail] = useState(''); const residents = useQuery(api.users.residents); const found = useQuery(api.users.findByEmail, email ? { email } : 'skip');
  return <><a className="back-link" href="/admin">← Resident room</a><Hero eyebrow="Designated admin / Access" title={<>The people<br /><em>in the room.</em></>} description="Grant review access when a resident joins. Existing application panels keep their assigned voters." /><form className="access-search" onSubmit={event => { event.preventDefault(); setEmail(search.trim()); }}><label htmlFor="resident-email">Find a registered account by verified email</label><div className="actions"><input type="email" id="resident-email" required value={search} onChange={event => setSearch(event.target.value)} /><button className="button">Find account</button></div></form>{email && found && <><h2>Search results</h2>{!found.length && <Notice>No account found. Ask the resident to sign in to the platform first.</Notice>}{found.map(person => <AccessRow key={person._id} person={person} />)}</>}<h2 className="social-heading">Active residents</h2>{residents?.map(person => <AccessRow key={person._id} person={person} />)}{residents?.length === 0 && <Notice>No active residents yet. Add registered accounts above before opening applications.</Notice>}</>;
}
function AccessRow({ person }: { person: Doc<'users'> }) {
  const [resident, setResident] = useState(person.resident); const [admin, setAdmin] = useState(person.admin); const [reason, setReason] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const save = useMutation(api.users.setAccess);
  return <form className="access-row" onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { await save({ userId: person._id, resident, admin, reason }); setMessage('Access updated.'); setReason(''); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }}><div><h3>{person.profile.name || 'New account'}</h3><p>{person.email}</p></div><label className="check"><input type="checkbox" checked={resident} onChange={event => setResident(event.target.checked)} />Active resident</label><label className="check"><input type="checkbox" checked={admin} onChange={event => setAdmin(event.target.checked)} />Designated admin</label><label className="access-reason">Reason for change<input required maxLength={2000} value={reason} onChange={event => setReason(event.target.value)} /></label><button className="button secondary" disabled={busy}>Save access</button>{message && <Notice>{message}</Notice>}{error && <Notice error>{error}</Notice>}</form>;
}
function EmailFailures() {
  const failures = useQuery(api.emails.failures); const retry = useMutation(api.emails.retry); const [error, setError] = useState('');
  if (!failures?.length) return null;
  return <section className="email-failures"><h2>Emails needing attention</h2>{failures.map(item => <div key={item._id}><p>{item.name} · {item.kind}<br /><small>{item.lastError}</small></p><button className="button secondary" onClick={() => retry({ id: item._id }).catch(err => setError(errorMessage(err)))}>Retry delivery</button></div>)}{error && <Notice error>{error}</Notice>}</section>;
}
function formatDate(value: number | null) { return value ? new Intl.DateTimeFormat('en-MY', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'Asia/Kuala_Lumpur' }).format(value) : '—'; }
